# Site information

site = { name = "Atipy", domain = "https://atipy.netlify.app/" }

# Build configuration

build = { publish = "out/" }

NEXT_USE_NETLIFY_EDGE = "true"

# Functions configuration
functions = [
    { name = "subscribe", src = "netlify/functions/subscribe.mts", type = "edge" },
]
