# Site information
site = { name = "Atipy", domain = "https://atipy.fr/" }

# Build configuration
build = { publish = "out/" }

NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Gestion des headers CORS pour les requêtes API
[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "POST, OPTIONS"
        Access-Control-Allow-Headers = "Content-Type"