# Site information
site = { name = "Atipy", domain = "https://atipy.fr/" }

# Build configuration
build = { publish = "out/" }

NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"