const typographyStyle = (theme) => ({
  '--tw-prose-body': 'black',
  '--tw-prose-headings': 'black',
  '--tw-prose-lead': 'black',
  '--tw-prose-links': theme('colors.a-blue'),
  '--tw-prose-bold': 'black',
  '--tw-prose-counters': 'black',
  '--tw-prose-bullets': 'black',
  '--tw-prose-hr': 'black',
  '--tw-prose-quotes': 'black',
  '--tw-prose-quote-borders': 'black',
  '--tw-prose-captions': 'black',
  '--tw-prose-code': 'black',
  '--tw-prose-pre-code': 'black',
  '--tw-prose-pre-bg': 'black',
  '--tw-prose-th-borders': 'black',
  '--tw-prose-td-borders': 'black',
  '--tw-prose-invert-body': 'white',
  '--tw-prose-invert-headings': 'white',
  '--tw-prose-invert-lead': 'white',
  '--tw-prose-invert-links': theme('colors.a-blue'),
  '--tw-prose-invert-bold': 'white',
  '--tw-prose-invert-counters': 'white',
  '--tw-prose-invert-bullets': 'white',
  '--tw-prose-invert-hr': 'white',
  '--tw-prose-invert-quotes': 'white',
  '--tw-prose-invert-quote-borders': 'white',
  '--tw-prose-invert-captions': 'white',
  '--tw-prose-invert-code': 'white',
  '--tw-prose-invert-pre-code': 'white',
  '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
  '--tw-prose-invert-th-borders': 'white',
  '--tw-prose-invert-td-borders': 'white',
  img: {
    marginTop: 0,
    marginBottom: 0,
    width: '100%',
    height: 'auto',
    objectFit: 'cover',
    borderRadius: 10,
  },
  h3: {
    fontSize: 'clamp(1.5rem, 2vw + 0.75rem, 2rem)',
    fontWeight: 'bold',
    lineHeight: 1,
    marginBottom: '1.5rem',
    color: 'currentColor',
  },
  h4: {
    fontSize: 'clamp(1.25rem, 1.25vw + 1rem, 1.563rem)',
    fontWeight: 'bold',
    lineHeight: 1.25,
    marginBottom: '1rem',
    color: 'currentColor',
  },
  h5: {
    fontSize: 'clamp(1.125rem, 2.5vw, 1.325rem)',
    fontWeight: 'bold',
    lineHeight: 1.25,
    marginBottom: '0.65rem',
    color: 'currentColor',
  },
  h6: {
    lineHeight: 1.25,
    marginBottom: '0.5rem',
    color: 'currentColor',
  },
  p: {
    fontSize: 'clamp(1rem, 2.5vw, 1.25rem)',
    lineHeight: 1.325,
    fontFamily: 'Roboto, sans-serif',
    color: 'currentColor',
    marginTop: '0',
    marginBottom: '1rem',
  },
  ul: {
    marginTop: '1rem !important',
    marginBottom: '1rem !important',
    fontFamily: 'Roboto, sans-serif',
  },
  li: {
    margin: 0,
    fontFamily: 'Roboto, sans-serif',
    fontSize: 'clamp(1rem, 2.5vw, 1.25rem)',
  },
  blockquote: {
    fontSize: 'clamp(1rem, 2.5vw, 1.25rem)',
    border: 'none',
    marginTop: '1rem !important',
    marginBottom: '1rem !important',
    paddingLeft: 0,
    fontFamily: 'Roboto, sans-serif',
  },
});

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  future: {
    hoverOnlyWhenSupported: true,
  },
  theme: {
    extend: {
      fontFamily: {
        primary: ['Atkinson Hyperlegible', 'sans-serif'],
        secondary: ['Roboto', 'sans-serif'],
      },
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        'a-yellow-light': '#FECF54',
        'a-yellow-dark': '#FDBE2D',
        'a-yellow-or': '#D7AD31',
        'a-red-light': '#E72E54',
        'a-red-dark': '#B02117',
        'a-green-light': '#51B1B0',
        'a-green-dark': '#077D8A',
        'a-blue-light': '#437ABE',
        'a-blue-dark': '#4559A4',
        'grey-100': '#F2F2F2',
        'grey-110': '#767676',
        'grey-140': '#6A6A6A',
        'grey-150': '#DDDDDD',
        'grey-160': '#00000029',
        'grey-bg-form': '#F0F0F0',
        'grey-t-form': '#9A9A9A',
        'black-160': '#0A0A0A',
        'a-divider': '#707070',
      },
      boxShadow: {
        'a-blue-light': '10px 10px 0px #437ABE',
        'a-blue-light-small': '6px 6px 0px #437ABE',
        'a-blue-dark': '10px 10px 0px #4559A4',
        'a-blue-dark-small': '6px 6px 0px #4559A4',
        'a-green-light': '10px 10px 0px #51B1B0',
        'a-green-light-small': '6px 6px 0px #51B1B0',
        'a-green-dark': '10px 10px 0px #077D8A',
        'a-green-dark-small': '6px 6px 0px #077D8A',
        'a-red-dark': '10px 10px 0px #B02117',
        'a-red-dark-small': '6px 6px 0px #B02117',
        'a-red-light': '10px 10px 0px #E72E54',
        'a-red-light-small': '6px 6px 0px #E72E54',
        'a-yellow-light': '10px 10px 0px #FECF54',
        'a-yellow-light-small': '6px 6px 0px #FECF54',
        'a-yellow-dark': '10px 10px 0px #FDBE2D',
        'a-yellow-dark-small': '6px 6px 0px #FDBE2D',
        'a-yellow-or': '10px 10px 0px #D7AD31',
        'project-card': '0px 0px 30px #DDDDDD',
        'project-filter': '0px 0px 10px #00000029',
      },
      fontSize: {
        body1: 'clamp(1rem, 2.5vw, 1.25rem)',
        body2: 'clamp(1rem, 2.5vw, 1.375rem)',
        body3: 'clamp(1rem, 0.8vw + 0.8rem, 1.563rem)',
      },
      borderWidth: {
        3: '3px',
        5: '5px',
      },
      screens: {
        desktop: '1920px',
        lmd: '960px',
        xxs: '321px',
        '1xl': '1440px',
        '3xl': '1680px',
      },
      maxWidth: {
        '8xl': '1440px',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: typographyStyle(theme),
        },
        lg: {
          css: typographyStyle(theme),
        },
        xl: {
          css: typographyStyle(theme),
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};
