backend:
  name: git-gateway
  branch: master
media_folder: public/media
public_folder: /media
collections:
  - name: 'layout'
    label: 'Layout'
    files:
      - label: 'Header'
        name: 'header'
        file: 'src/data/layout/header.md'
        fields:
          - label: Navigation
            hint: Vous pouvez changer l'ordre des différents element
            name: mainNavigation
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Link,
                  name: link,
                  widget: select,
                  options:
                    [
                      '/agence',
                      '/expertises',
                      '/realisations',
                      '/posts',
                      '/contact',
                    ],
                }
      - label: 'Footer'
        name: 'footer'
        file: 'src/data/layout/footer.md'
        fields:
          - label: Menu text 1
            name: menuText1
            widget: object
            fields:
              - { label: Titre, name: title, widget: string }
              - label: Ligne
                hint: Vous pouvez changer l'ordre des différentes lignes
                name: rows
                widget: list
                fields:
                  - {
                      label: Lien 1,
                      name: link1,
                      widget: object,
                      fields:
                        [
                          { label: Label, name: label, widget: string },
                          {
                            label: Url,
                            name: url,
                            widget: select,
                            options: ['/'],
                          },
                        ],
                    }
                  - {
                      label: Lien 2,
                      name: link2,
                      widget: object,
                      fields:
                        [
                          { label: Label, name: label, widget: string },
                          {
                            label: Url,
                            name: url,
                            widget: select,
                            options: ['/'],
                          },
                        ],
                    }
          - label: Menu text 2
            name: menuText2
            widget: object
            fields:
              - { label: Titre, name: title, widget: string }
              - label: Ligne
                hint: Vous pouvez changer l'ordre des différentes lignes
                name: rows
                widget: list
                fields:
                  - {
                      label: Lien 1,
                      name: link1,
                      widget: object,
                      fields:
                        [
                          { label: Label, name: label, widget: string },
                          { label: Url, name: url, widget: string },
                        ],
                    }
                  - {
                      label: Lien 2,
                      name: link2,
                      widget: object,
                      fields:
                        [
                          { label: Label, name: label, widget: string },
                          { label: Url, name: url, widget: string },
                        ],
                    }
          - label: Menu social
            name: menuSocial
            widget: object
            fields:
              - { label: Titre, name: title, widget: string }
              - label: Lien
                hint: Vous pouvez changer l'ordre des différents liens
                name: rows
                widget: list
                fields:
                  - {
                      label: Type,
                      name: type,
                      widget: select,
                      options: ['instagram', 'linkedin', 'twitter'],
                    }
                  - { label: Url, name: url, widget: string }
  - name: 'Pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/data/pages/home.md'
        widget: object
        fields:
          - label: Section 1 - Banner
            name: bannerData
            widget: object
            fields:
              - {
                  label: Titre,
                  name: title,
                  widget: markdown,
                  buttons: [bold, italic],
                  modes: [rich_text],
                  hint: "Utiliser l'italic pour utliser la font Atkinson",
                  editor_components: [],
                }
          - label: Section 2 - Intro
            name: introData
            widget: object
            fields:
              - {
                  label: Titre,
                  name: title,
                  widget: markdown,
                  buttons: [bold, italic],
                  modes: [rich_text],
                  hint: "Utiliser l'italic pour utliser la font Atkinson",
                  editor_components: [],
                }
              - label: Bouton
                name: button
                widget: object
                fields:
                  - { label: Label, name: label, widget: string }
                  - {
                      label: Url,
                      name: url,
                      widget: select,
                      options:
                        [
                          '/agence',
                          '/expertises',
                          '/realisations',
                          '/posts',
                          '/contact',
                        ],
                    }
          - label: Section 3 - Offres
            name: offersData
            widget: object
            fields:
              - label: Card
                hint: Vous pouvez changer l'ordre des différentes card
                name: cards
                widget: list
                fields:
                  - {
                      label: Type,
                      name: type,
                      widget: select,
                      options:
                        [
                          { label: Accessibilité, value: ACCESIBILITY },
                          { label: Design, value: DESIGN },
                          { label: Digital, value: DIGITAL },
                          { label: Conseils et formations, value: CONSEIL },
                        ],
                    }
                  - { label: Titre, name: title, widget: string }
                  - {
                      label: Text,
                      name: body,
                      widget: markdown,
                      buttons: [],
                      modes: [rich_text],
                      editor_components: [],
                    }
                  - label: Bouton
                    name: button
                    widget: object
                    fields:
                      - { label: Label, name: label, widget: string }
  - name: posts
    label: Post
    folder: src/data/posts
    create: true
    slug: '{{slug}}'
    fields:
      - label: Titre
        name: title
        widget: string
      - label: Date de publication
        name: date
        widget: datetime
      - label: Contenu
        name: body
        widget: markdown
