backend:
  name: git-gateway
  branch: master
media_folder: public/media
public_folder: /media
collections:
  - name: posts
    label: Post
    folder: src/posts
    create: true
    slug: "{{slug}}"
    fields:
      - label: Titre
        name: title
        widget: string
      - label: Date de publication
        name: date
        widget: datetime
      - label: Contenu
        name: body
        widget: markdown
