local_backend: true

backend:
  name: git-gateway
  branch: master
media_folder: public/media
public_folder: /media
collections:
  - name: "layout"
    label: "Layout"
    files:
      - label: "Header"
        name: "header"
        file: "src/data/layout/header.md"
        fields:
          - label: Navigation
            hint: Vous pouvez changer l'ordre des différents element
            name: mainNavigation
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Link,
                  name: link,
                  widget: select,
                  options:
                    [
                      "/agence",
                      "/expertises",
                      "/realisations",
                      "/posts",
                      "/contact",
                    ],
                }
  - name: posts
    label: Post
    folder: src/data/posts
    create: true
    slug: "{{slug}}"
    fields:
      - label: Titre
        name: title
        widget: string
      - label: Date de publication
        name: date
        widget: datetime
      - label: Contenu
        name: body
        widget: markdown
